### ISSUE TITLE
retirer la flêche "retour en haut" quand .. on est en haut

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/breizhcamp#13]
ça à l'air con comme demande, mais chez moi ça donne ça 

![image](https://cloud.githubusercontent.com/assets/132757/6926894/e065830c-d7e9-11e4-8238-3868e495a837.png)

**Comment by LostInBrittany** [comment]
Pour le moment j'ai mis une bordure pour que ça se remarque un peu plus, je vais corriger avec du JS quand j'aurai un moment.
