### ISSUE TITLE
Liens editions précédentes

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/breizhcamp#6]
toujours dans le github (page 2014.html), mais écrasé par le nouveau site.

**Comment by LostInBrittany** [comment]
Ils sont toutes là (2014, 2013, 2012) ?
Si oui, je fais un peu d’archéogitlogie et je m'en occupe de changer l'arborescence, ce soir...

**Comment by ndeloof** [comment]
oui, sinon t'emmerde pas, vire ça et met juste un lien "édition précédente" vers https://www.youtube.com/playlist?list=PLHWl6dPnEb4l9S-nl4od10OkTOyZEn5Ef
