### ISSUE TITLE
Jambe du "p" de BreizhCamp bizarrement décalée

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/breizhcamp#7]

**Comment by LostInBrittany** [comment]
Où ? Dans le logo ?

**Comment by ndeloof** [comment]
oui dans le logo
![image](https://cloud.githubusercontent.com/assets/132757/6894158/6d5fceb0-d6d3-11e4-891f-91eed612d788.png)

**Comment by LostInBrittany** [comment]
Wow, bonne vue ! Je corrige...
