### ISSUE TITLE
Bouton de feedback

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/breizhcamp#9]
un peu comme sur http://www.leankanban.fr/

**Comment by LostInBrittany** [comment]
Tu parles du pavez en bas "Suivez-nous" ? Le pavé social networks ?

**Comment by ndeloof** [comment]
mince, ils a disparu :-\
c'était un bouton latéral "feedback" comme on en trouve, par exemple sur https://console.cloudbees.com/a/breizhcamp/home

**Comment by LostInBrittany** [comment]
O.K., j'ai vu le bouton. Tu veux qu'il ouvre un formulaire qui nous envoie un mail ? Ou un simple lien mailto ?

**Comment by ndeloof** [comment]
un mailto: ça serait déjà pas mal

2015-03-30 21:01 GMT+02:00 Horacio Gonzalez notifications@github.com:
